[phases.setup]
providers = ["nodejs_24"]

[phases.install]
onlyIncludeFiles = [
  "package.json",
  "bun.lock",
]

[start]
cmd = "bun .next/standalone/server.js"
runImage = "oven/bun"
onlyIncludeFiles = [
  ".next",
]
